version: "3.7"


services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - taketae_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - taketae_static:/data/static/
      - taketae_media:/data/media/
      - taketae_log:/var/log/nginx/

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
      - taketae_log:/var/log/nginx/
    ports:
      - 7890:7890
    command: /var/log/nginx/taketae_access.log -o /var/log/nginx/report.html --log-format COMBINED --real-time-html

  django:
    image: taketae_django:5
    networks:
      - taketae_network
    volumes:
      - taketae_static:/home/web-app2/staticfiles
      - taketae_media:/home/web-app2/media
    secrets:
      - django_secret_key
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - taketae_network
    volumes:
      - taketae_maria:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FIL E: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  taketae_network:

volumes:
  taketae_static:
  taketae_media:
  taketae_maria:
  taketae_log:

secrets:
  django_secret_key:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true