version: "3.7"


services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - taketae_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - taketae_static:/data/static/
      - taketae_media:/data/media/

  django:
    image: taketae_django:4
    networks:
      - taketae_network
    volumes:
      - taketae_static:/home/web-app2/staticfiles
      - taketae_media:/home/web-app2/media
    secrets:
      - django_secret_key

  mariadb:
    image: mariadb:10.5
    networks:
      - taketae_network
    volumes:
      - taketae_maria:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: qlalfqjsgh@
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: qlalfqjsgh@

networks:
  taketae_network:

volumes:
  taketae_static:
  taketae_media:
  taketae_maria:

secrets:
  django_secret_key:
    external: true